version: 2
updates:
  - package-ecosystem: maven
    directory: "/app"
    schedule:
      interval: "weekly"
      time: '10:00'
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '10:00'
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
      time: '10:00'
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
