name: Build and Push Docker Images

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yaml'
      - 'pom.xml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yaml'
      - 'pom.xml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Spring Boot image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository }}/app:${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
